name: Build and upload latest datafusion-comet jar

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Build jars
        run: make release
      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: comet.jar
          path: "spark/target/comet-spark-*-SNAPSHOT.jar"
          overwrite: true
